import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import NavBar from "../components/dashboard/NavBar";
import Providers from "../context/Provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialIsAuthenticate = cookieStore.get("accessToken")?.value ?? null;
  console.log("Initial auth state from cookies:", initialIsAuthenticate);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers cookieToken={initialIsAuthenticate}>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
